#ifndef _RICERMACTIMERS_H_
#define _RICERMACTIMERS_H_

enum RicerMacTimer {
	RICER_MAC_TIMER_WAIT_FOR_RADIO_RX_TRANSITION_DELAY = 1,
	RICER_MAC_TIMER_WAIT_FOR_RADIO_SLEEP_TRANSITION_DELAY = 2,
	RICER_MAC_TIMER_BACKOFF_FOR_CCA = 3,
	RICER_MAC_TIMER_LISTEN_FOR_DATA = 4,
	RICER_MAC_TIMER_WAKE_FOR_RECEIVE = 5,
	RICER_MAC_TIMER_SEND_TIMEOUT = 6,
	RICER_MAC_TIMER_SEND_BACKOFF = 7,
	RICER_MAC_TIMER_WAIT_FOR_ACK = 8,
	RICER_MAC_TIMER_WAIT_FOR_RADIO_TX_COMPLETE = 9
};

#endif //_RICERMACTIMERS_H_